//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public Competition()
        {
            this.CompetitionGolfer = new HashSet<CompetitionGolfer>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public System.DateTime cDate { get; set; }
        public string info { get; set; }
        public System.DateTime signUpFrom { get; set; }
        public System.DateTime signUpTo { get; set; }
        public int Person_IDc { get; set; }
        public int playersPerTime { get; set; }
        public int CompeteClass_ID { get; set; }
        public int NumberOfHoles { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
    
        public virtual CompeteClass CompeteClass { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<CompetitionGolfer> CompetitionGolfer { get; set; }
    }
}
