//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public Gender()
        {
            this.Person = new HashSet<Person>();
            this.Slope = new HashSet<Slope>();
        }
    
        public int Id { get; set; }
        public string genderName { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
        public virtual ICollection<Slope> Slope { get; set; }
    }
}
