//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Golfer
    {
        public Golfer()
        {
            this.TeeTimeDateGolfer = new HashSet<TeeTimeDateGolfer>();
        }
    
        public int Id { get; set; }
        public string golfID { get; set; }
        public string HCP { get; set; }
        public int Person_ID { get; set; }
        
        [JsonIgnore]
        public virtual Person Person { get; set; }
        [JsonIgnore]
        public virtual ICollection<TeeTimeDateGolfer> TeeTimeDateGolfer { get; set; }
    }
}
