//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golfer
    {
        public int Id { get; set; }
        public string golfID { get; set; }
        public string HCP { get; set; }
        public Nullable<int> Person_ID { get; set; }
    }
}
