//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoleStats
    {
        public int Id { get; set; }
        public int CompetitionGolfer_ID { get; set; }
        public int Hole_ID { get; set; }
        public int stroaks { get; set; }
    
        public virtual CompetitionGolfer CompetitionGolfer { get; set; }
        public virtual Hole Hole { get; set; }
    }
}
