//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hole
    {
        public Hole()
        {
            this.HoleStats = new HashSet<HoleStats>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public int yellowRange { get; set; }
        public int redRange { get; set; }
        public int par { get; set; }
        public int HCPind { get; set; }
    
        public virtual ICollection<HoleStats> HoleStats { get; set; }
    }
}
