//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public Images()
        {
            this.NewsArticleImage = new HashSet<NewsArticleImage>();
        }
    
        public int Id { get; set; }
        public string imgURL { get; set; }
    
        public virtual ICollection<NewsArticleImage> NewsArticleImage { get; set; }
    }
}
