//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsArticleImage
    {
        public int Id { get; set; }
        public Nullable<int> NewsArticle_ID { get; set; }
        public Nullable<int> Images_ID { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual NewsArticle NewsArticle { get; set; }
    }
}
