//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsArticle
    {
        public NewsArticle()
        {
            this.NewsArticleImage = new HashSet<NewsArticleImage>();
        }
    
        public int Id { get; set; }
        public string header { get; set; }
        public string content { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<System.DateTime> newsDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<NewsArticleImage> NewsArticleImage { get; set; }
    }
}
