//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dsuteam4Entities1 : DbContext
    {
        public dsuteam4Entities1()
            : base("name=dsuteam4Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Golfer> Golfer { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<AdminPerson> AdminPerson { get; set; }
        public DbSet<TeeDate> TeeDate { get; set; }
        public DbSet<TeeTime> TeeTime { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<Images> Images { get; set; }
        public DbSet<NewsArticle> NewsArticle { get; set; }
        public DbSet<NewsArticleImage> NewsArticleImage { get; set; }
        public DbSet<AdminType> AdminType { get; set; }
        public DbSet<MemberType> MemberType { get; set; }
        public DbSet<TeeTimeDateGolfer> TeeTimeDateGolfer { get; set; }
        public DbSet<TeeTimeDate> TeeTimeDate { get; set; }
    }
}
