//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace golf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeeTimeDateGolfer
    {
        public int Id { get; set; }
        public int TeeTimeDate_ID { get; set; }
        public int Golfer_ID { get; set; }
    
        public virtual Golfer Golfer { get; set; }
        public virtual TeeTimeDate TeeTimeDate { get; set; }
    }
}
